blank_issues_enabled: false
contact_links:
  - name: General Questions
    url: https://github.com/dawn-bridge-labs/dawn-bridge-core/discussions
    about: Ask questions and share ideas in Discussions.
